### ISSUE TITLE
elided lifetime has a name warnings

### ISSUE THREAD

**Issue by Sachilearns** [xelis-project/xelis-blockchain#102]
ubuntu 20.04

cargo build --release  
 wallet generates these warnings can't seem to fix, help needed

warning: elided lifetime has a name
   --> xelis_common/src/prompt/command.rs:192:40
    |
192 |     pub fn get_prompt<'a>(&'a self) -> &ShareablePrompt {
    |                       --               ^ this elided lifetime gets resolved as `'a`
    |                       |
    |                       lifetime `'a` declared here
    |
    = note: `#[warn(elided_named_lifetimes)]` on by default

warning: `xelis_common` (lib) generated 1 warning
   Compiling xelis_wallet v1.15.0 (/home/dapa1/xelis-blockchain/xelis_wallet)
warning: elided lifetime has a name
   --> xelis_wallet/src/wallet.rs:518:44
    |
518 |     pub fn get_api_server<'a>(&'a self) -> &Mutex<Option<APIServer<Arc<Self>>>> {
    |                           --               ^ this elided lifetime gets resolved as `'a`
    |                           |
    |                           lifetime `'a` declared here
    |
    = note: `#[warn(elided_named_lifetimes)]` on by default

warning: elided lifetime has a name
    --> xelis_wallet/src/wallet.rs:1060:46
     |
1060 |     async fn get_public_key(&self) -> Result<&DecompressedPublicKey, Error> {
     |                             -                ^ this elided lifetime gets resolved as `'life0`
     |                             |
     |                             lifetime `'life0` declared here

warning: elided lifetime has a name
   --> xelis_wallet/src/api/xswd.rs:153:46
    |
153 |     async fn get_public_key(&self) -> Result<&DecompressedPublicKey, Error>;
    |                             -                ^ this elided lifetime gets resolved as `'life0`
    |                             |
    |                             lifetime `'life0` declared here

**Comment by Slixe** [comment]
Hi, what is your rust version? Which branch are you trying to build and at which commit?

**Comment by Sachilearns** [comment]
rustc 1.85.0-nightly (dff3e7ccd 2024-11-26)
zip file downloaded
build all

**Comment by Slixe** [comment]
This has been fixed in network-upgrade branch.
