### ISSUE TITLE
daemon build fails 

### ISSUE THREAD

**Issue by k7n2g** [xelis-project/xelis-blockchain#109]
**Describe the bug**
error: failed to run custom build command for `xelis_common v1.16.0 

Caused by:
  process didn't exit successfully: `/var/www/html/xelis/target/release/build/xelis_common-8f4c886017fa5f33/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at xelis_common/build.rs:14:14:
  Failed to execute git command: Os { code: 2, kind: NotFound, message: "No such file or directory" }

**Version used**
[v1.16.0](https://github.com/xelis-project/xelis-blockchain/commit/3253c5a971b37e6b9fca5cdf2f0c6f224684f9e0)

**To Reproduce**
xelis/xelis_daemon# cargo build --bin xelis_daemon --release

**Expected behavior**
Daemon script to build.

**Additional context**
error: failed to run custom build command for `xelis_common v1.16.0 (/var/www/html/xelis/xelis_common)`

OS is ubuntu 22.04  3Tb HD  60Gb memory

Working rust installation and cargo updated   am i missing something here

**Comment by Slixe** [comment]
You need to install git for correct building

**Comment by k7n2g** [comment]
Thank you slixe much appreciated  Happy new year to you
