### ISSUE TITLE
Consider using a different function for fast-hash

### ISSUE THREAD

**Issue by duggavo** [xelis-project/xelis-blockchain#17]
At the time of writing, Xelis is using SHA3/Keccak for block hashes.

Since block time will be very small (blockDAG), it may be interesting to explore faster hash functions for the use in Xelis.
Especially considering Keccak is slower than SHA256. Synchronization times can be slowed down significantly by the hashing.

Some notable alternatives:
- Blake2 (especially blake2b, maybe a truncated version?)
- Blake3

Both Blake2b and Blake3 have been successfully used in mainnet in several crypto projects.

**Comment by Slixe** [comment]
Xelis is using Keccak256 for TX and Block IDs.
Changing it to another (faster) hashing algorithm is something planned but didn’t took time to compare all algorithms. Blake looks a great choice.

POW Hash algorithm is still under work, but for final release it will not be keccak.

**Comment by Slixe** [comment]
XELIS will use Blake3 for next release.
