### ISSUE TITLE
Dubious necessity of an uint128 for timestamp values

### ISSUE THREAD

**Issue by duggavo** [xelis-project/xelis-blockchain#18]
As seen on https://github.com/xelis-project/xelis-blockchain/blob/dev/xelis_common/src/block/mod.rs#L50 , Xelis seems to be using an unsigned 128-bit value for representing millisecond timestamps.

The necessity of this is dubious.
An unsigned 64-bit integer (uint64 aka u64) can store 2^64 (`18446744073709551616`) values.
It means that it can store 584942417 years in milliseconds.

So, I think an uint64 is more than enough for the scope of this project.

8 bytes per block, with an average of 2 blocks per second, is around 504 MB a year.

EDIT:
8 bytes per block, with an average of 1 block every 15 seconds, is around 2.1 MB a year.

**Comment by Slixe** [comment]
XELIS will have only a average block time of 15s. With side block it may be reduced to 10-13s.

milliseconds timestamp will allow a much more precise difficulty adjustment

**Comment by duggavo** [comment]
> XELIS will have only a average block time of 15s. With side block it may be reduced to 10-13s.

Thank you. I have corrected the text above.

> milliseconds timestamp will allow a much more precise difficulty adjustment

This is absolutely right. What I am saying is that an uint64 is enough to store millisecond timestamp, since an uint64 value can store 584942417 years in milliseconds (an uint128 can store ~ 1.08e+28 years).

**Comment by Slixe** [comment]
Implemented in the upcoming release
