### ISSUE TITLE
Peerlist possible corruption

### ISSUE THREAD

**Issue by duggavo** [xelis-project/xelis-blockchain#28]
Xelis-daemon's peerlist is only saved on graceful shutdown.

This can cause loss of peers data, if the daemon is shut down abruptly, and significant load to seed nodes.

Consider saving the peerlist more frequently during the normal operation of daemon.

Perhaps moving peerlist to a safer, faster database than full JSON rewrites, which can cause corruption.

**Comment by Slixe** [comment]
Agree, this has been to rewritten, with high count of peers, this can use a lot of memory after some point.

**Comment by Slixe** [comment]
Fixed in dev branch

Usage of sled DB also help to reduce memory usage
