### ISSUE TITLE
cpu thread settings

### ISSUE THREAD

**Issue by agarwood777** [xelis-project/xelis-blockchain#38]
Please tell me how to set the threads of the CPU when using the CPU so that the computer will not be fully loaded.

**Comment by Slixe** [comment]
https://docs.xelis.io/getting-started/configuration#numbers-of-threads

> ### Numbers of Threads
>Set the numbers of threads to use for the miner. By default, the numbers of threads is set to the number of logical cores of the CPU.
> Minimum is 1 and maximum is 255.
> Example to set the numbers of threads to 4: ./xelis_miner --num-threads 4.
