### ISSUE TITLE
what is it ? is this a new chain like solana ，sui ?

### ISSUE THREAD

**Issue by zgimszhd61** [xelis-project/xelis-blockchain#49]

**Comment by xray7474** [comment]
> _No description provided._

https://xelis.io/#socials

**Comment by Slixe** [comment]
XELIS is a new project with BlockDAG and Homomorphic Encryption, it aims to have an egalitarian POW for GPUs and CPUs, and to release Smart Contracts and Confidentials Assets/tokens on the chain.

More at https://docs.xelis.io
