### ISSUE TITLE
Non-interactive and no colors

### ISSUE THREAD

**Issue by duggavo** [xelis-project/xelis-blockchain#50]
for systemd services, would be useful to have a flag similar to monerod's `--non-interactive`, for both daemon and wallet, which prevents readline "prompting".

Also --no-colors could be useful for systems that do not support color codes (journalctl logs, for example)

**Comment by Slixe** [comment]
They got both implemented in #63 
```
      --disable-interactive-mode
          Disable terminal interactive mode You will not be able to write CLI commands in it or to have an updated prompt
          
      --disable-log-color
          Disable the usage of colors in log
```
