### ISSUE TITLE
Wallet is in offline mode

### ISSUE THREAD

**Issue by arth25** [xelis-project/xelis-blockchain#55]
Not able to switch to online mode 
![error](https://github.com/xelis-project/xelis-blockchain/assets/76473067/706dccd9-9579-4aa6-ad04-cb965197065e)

**Comment by arth25** [comment]
![Uploading error.JPG…]()

**Comment by arth25** [comment]
![error](https://github.com/xelis-project/xelis-blockchain/assets/76473067/c65e9348-fb65-49e2-b460-63fe0fe3368b)

**Comment by Slixe** [comment]
are you running a node on your device?

**Comment by arth25** [comment]
yes

**Comment by arth25** [comment]
Everything is now properly running but the balance as well as Accepted block is not updating. I started almost 4 hours ago still it showing me 0. 

![error](https://github.com/xelis-project/xelis-blockchain/assets/76473067/7d439a78-186d-4649-9274-5ec001646038)
