### ISSUE TITLE
miner unable to connect to wss due to certifcate

### ISSUE THREAD

**Issue by shafrir** [xelis-project/xelis-blockchain#59]
Hi
miner unable to connect to wss due to certifcate
it`s windows instance in aws
INFO                     xelis_miner > Trying to connect to wss://node.xelis.io
ERROR                    xelis_miner > Error while connecting to wss://node.xelis.io: IO error: invalid peer certificate: UnknownIssuer
WARN                     xelis_miner > Trying to connect to WebSocket again in 10 seconds...

**Comment by Slixe** [comment]
This is fixed since few versions.

Reopen an issue if you still have the error.
