### ISSUE TITLE
Stuck At block 173990

### ISSUE THREAD

**Issue by kugimiya530** [xelis-project/xelis-blockchain#69]
i sync from yesterday , version is 1.12

and stuck at 173990 for maybe couple hours

any idea?
![Uploading xelis.png…]()

**Comment by psyble** [comment]
I have same issue too

![111](https://github.com/xelis-project/xelis-blockchain/assets/63038972/cedbfd76-a1ac-48af-9a62-ad49d9cbe9c3)

**Comment by Slixe** [comment]
Please try https://github.com/xelis-project/xelis-blockchain/issues/75#issuecomment-2209640024
