### ISSUE TITLE
how write the bat to start?

### ISSUE THREAD

**Issue by mtmtmt123** [xelis-project/xelis-blockchain#70]
how write the bat to start mining?? thanks

**Comment by Slixe** [comment]
`./xelis_miner --miner-address=<your wallet> --daemon-address=<daemon address>`

Example for testnet:
`./xelis_miner -miner-address=xet:nrza6ty3dfdd8yxxz3ecvm8nlvu4dhkrupeq5uypxnxxnj0nxfrsqukn80l --daemon-address=testnet-node.xelis.io`
