### ISSUE TITLE
What command can be used to restore the interface on the Ubantu system after SSH is closed and reconnected?

### ISSUE THREAD

**Issue by zsvvv** [xelis-project/xelis-blockchain#71]
What command can be used to restore the interface on the Ubantu system after SSH is closed and reconnected?
![2222222222222](https://github.com/xelis-project/xelis-blockchain/assets/70995280/aa8fa608-4e57-416e-a328-0262360c60c9)

**Comment by M3T4LG0R1LL4** [comment]
This has nothing to do with Xelis it is a linux operations issue. However, I suggest you use either screen or tmux to run your node. You need a little bit of research:

Screen: https://www.howtogeek.com/662422/how-to-use-linuxs-screen-command/
Tmux: https://www.howtogeek.com/671422/how-to-use-tmux-on-linux-and-why-its-better-than-screen/

Even better would be to use a systemd service and have your node start in a screen session on system boot.

**Comment by Slixe** [comment]
thanks for handling this issue @M3T4LG0R1LL4, closing.
