### ISSUE TITLE
Wallet can become and remain offline

### ISSUE THREAD

**Issue by duggavo** [xelis-project/xelis-blockchain#73]
This is a (very) rare bug that only happened once in many days.
I think that maybe this is because the wallet isn't reconnecting to websocket?
```
ERROR  skoof_wallet::network_handler > Error while syncing: Error while retrieving info from chain
WARN   skoof_wallet::network_handler > Daemon is online but we couldn't sync, trying again in 5 seconds
```
Unfortunately I don't have more logs. This error message was repeated for 5 seconds indefinitely. The issue is very hard to reproduce,

Another issue which is easier to reproduce:
1. Start daemon
2. Start wallet
3. Stop the daemon
4. Start the daemon again
5. The wallet won't reconnect. It will continue to say that the daemon is offline.

**Comment by roushanroy22** [comment]
Hyy

**Comment by xdjxdaveyx** [comment]
After creating wallet the wallet app was not able to go online at all - I checked security in Windows 11 and there is no blocking (os error 10061)

**Comment by xdjxdaveyx** [comment]
also, no easy way to copy wallet address from the command line as text select is disabled?

**Comment by Slixe** [comment]
> also, no easy way to copy wallet address from the command line as text select is disabled?
That shouldn't be the case, which terminal app are you using ?


> After creating wallet the wallet app was not able to go online at all - I checked security in Windows 11 and there is no blocking (os error 10061)
Do you have a local node running ? if not, you can use following command in wallet: `online_mode node.xelis.io` or with CLI launch option `--daemon-address=node.xelis.io`

**Comment by Slixe** [comment]
> This is a (very) rare bug that only happened once in many days. I think that maybe this is because the wallet isn't reconnecting to websocket?
> 
> ```
> ERROR  skoof_wallet::network_handler > Error while syncing: Error while retrieving info from chain
> WARN   skoof_wallet::network_handler > Daemon is online but we couldn't sync, trying again in 5 seconds
> ```
> 
> Unfortunately I don't have more logs. This error message was repeated for 5 seconds indefinitely. The issue is very hard to reproduce,
> 
> Another issue which is easier to reproduce:
> 
> 1. Start daemon
> 2. Start wallet
> 3. Stop the daemon
> 4. Start the daemon again
> 5. The wallet won't reconnect. It will continue to say that the daemon is offline.

Can you retry with latest version ? Network handler got reworked a bit

**Comment by xdjxdaveyx** [comment]
> > also, no easy way to copy wallet address from the command line as text select is disabled?
> 
> That shouldn't be the case, which terminal app are you using ?
> 
> > After creating wallet the wallet app was not able to go online at all - I checked security in Windows 11 and there is no blocking (os error 10061)
> 
> Do you have a local node running ? if not, you can use following command in wallet: `online_mode node.xelis.io` or with CLI launch option `--daemon-address=node.xelis.io`

I've sorted it now thanks for the tip. I ran the daemon application (part of the windows download bundle) first and then found the wallet app came online. I then right clicked on the top left of the cmd.exe wallet app and exported the text to get the wallet address. All good now - many thanks @Slixe

**Comment by duggavo** [comment]
Closing as this issue doesn't seem to occur anymore with new versions.
