### ISSUE TITLE
Running Xelis Blockchain Locally: Clarification on Projects and Frontend

### ISSUE THREAD

**Issue by frozenmafia** [xelis-project/xelis-blockchain#77]
Hi there,

First of all, I want to say that this project is really awesome! I've been able to run the xels-blockchain part on my PC without any issues, but I'm a bit confused about the rest of the setup.

I see that Xelis has a lot of different projects, and I'm unsure about which ones I need to clone to get the complete Xelis environment running locally. Could anyone provide a list of the projects I need to clone to run the entire Xelis suite on my local machine?

Additionally, is there any frontend available for Xelis? If so, which project should I look at for setting that up?

I would greatly appreciate any guidance on this. I’m eager to set up the complete software myself and start exploring.

Thanks in advance!

**Comment by Slixe** [comment]
hey there, thank you!

GUI Wallet named Genesix: https://github.com/xelis-project/xelis-genesix-wallet

Block Explorer: https://github.com/xelis-project/xelis-explorer

and from current repo, you can run the daemon/node :) 

You may find more infos here: https://docs.xelis.io

**Comment by frozenmafia** [comment]
> Hi there,
> 
> First of all, I want to say that this project is really awesome! I've been able to run the xels-blockchain part on my PC without any issues, but I'm a bit confused about the rest of the setup.
> 
> I see that Xelis has a lot of different projects, and I'm unsure about which ones I need to clone to get the complete Xelis environment running locally. Could anyone provide a list of the projects I need to clone to run the entire Xelis suite on my local machine?
> 
> Additionally, is there any frontend available for Xelis? If so, which project should I look at for setting that up?
> 
> I would greatly appreciate any guidance on this. I’m eager to set up the complete software myself and start exploring.
> 
> Thanks in advance!
