### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by xdjxdaveyx** [xelis-project/xelis-blockchain#79]
**Is your feature request related to a problem? Please describe.**
Lack of version ID in each tag filesystem

**Describe the solution you'd like**
A changelog file with each release

**Describe alternatives you've considered**
Version number file at least on folder name or in a file

**Additional context**
Would help with knowing when to update or suggest changes

**Comment by Slixe** [comment]
I'm trying to keep a changelog up to date in the pull requests where it's fully explained, but maybe having a CHANGELOG.md file which contains all changes can be useful.

Will take note for next release.

**Comment by xdjxdaveyx** [comment]
Much appreciated, thanks for taking note.

**Comment by Slixe** [comment]
Fixed in https://github.com/xelis-project/xelis-blockchain/commit/aed29780e439f32fc3ed14980a4921f6ad7e0647
