### ISSUE TITLE
GPU access for miner

### ISSUE THREAD

**Issue by markovAutomorphism** [xelis-project/xelis-blockchain#88]
Hi,

I'd like to start off by saying that what I have seen of this project so far is fantastic. I really enjoy the layout of the command line interface you have set up here. I am currently trying to run the daemon and miner after having created an address with the wallet on a different machine. 

I am trying to get the miner to use my RTX 4090 GPU but I am not quite sure what to do: any tips or pointers?

**Comment by Slixe** [comment]
Thank you!

There is no official GPU miner, so you will have to check with third-party closed-source miners like OneZeroMiner or Rigelminer.

Be careful of scams and use at your own risk.

**Comment by markovAutomorphism** [comment]
Thank you for your fast reply! It's good to know that the miner is designed for CPU only; I know now that I encounter no errors and  everything seems to run really smoothly. 

Have you tested any GPU functionality or know where you would start for integrating such a thing?
